# Generated by Django 4.2.4 on 2023-08-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_dish_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='preparing', max_length=20),
        ),
    ]
