# Generated by Django 4.2.4 on 2023-08-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0003_remove_order_status_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
