# Generated by Django 4.2.4 on 2023-08-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
    ]
